import { Inter, Poller_One, Poppins } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const pollerOne = Poller_One({ subsets: ["latin"], weight: ["400"] });
const poppins = Poppins({subsets: ["latin"], weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800"]})



export const metadata = {
  title: "Lucas G Soria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${pollerOne.className} ${poppins.className}`}>{children}</body>
    </html>
  );
}
